core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('visual/',include('visual.urls', namespace='visual'))
]

visual/urls.py
from django.urls import path
from .views import VisualListView

app_name="visual"

urlpatterns = [
    path('', VisualListView.as_view(), name="home")
]

visual/models.py
from django.db import models

# Create your models here.

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {
            
        }
        return render(request, 'login.html',context)

visual/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.
class VisualListView(View):
    def get(self, request, *args, **kwargs):
        context={
            
        }
        return render(request, 'index.html', context)

templates/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Visual Management</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans|Bebas+Neue&display=swap"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css'><link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div id="container" class="container active">
	<header class="header">
		<div class="ctn-logo">
			<button type="button" id="btn-menu" class="btn-menu">
				<i class="fas fa-bars"></i>
			</button>
			
			<a href="javascript:void(0);"> <!--class="logo"-->
				<!-- <i class="fas fa-play"></i>-->
				<span>
					MAX
				</span>
			</a>
		</div>
		
		<div class="search-bar">
			<input type="text" placeholder="Buscar">
			
			<button type="submit">
				<i class="fas fa-search"></i>
			</button>
		</div>
		
		<div class="ctn-btns-header">
			<button type="button">
				<i class="fas fa-upload"></i>
			</button>
			
			<button type="button">
				<i class="fas fa-th"></i>
			</button>
			
			<button type="button">
				<i class="fas fa-bell"></i>
			</button>
			
			<a href="javascript:void(0);" class="btn-avatar">
				<img src="http://crianbluff.com/imgs/imgs-general/modals/modal-creator-web/avatar-creator-web/avatar-creator-web.jpg" alt="Avatar" title="Avatar">
			</a>
		</div>
	</header>
	
	<nav class="menu-lateral">
		<a href="javascript:void(0);" class="active">
			<i class="fas fa-home"></i>
			Página Principal
		</a>
		
		<a href="javascript:void(0);">
			<i class="fas fa-fire"></i>
			Monitor de Planta
		</a>
		
		<a href="javascript:void(0);">
			<i class="fas fa-star"></i>
			Monitor de Ordenes <br>
			de Producción
		</a>
		
		<a href="javascript:void(0);">
			<i class="fas fa-folder"></i>
			Monitor de Materiales <br>Emitidos a Una Orden de Trabajo
		</a>
		
		<a href="javascript:void(0);">
			<i class="fas fa-folder"></i>
			Monitor Despacho Pedidos <br> Ventas
		</a>
		
		<a href="javascript:void(0);">
			<i class="fas fa-folder"></i>
			Monitor de Compras
		</a>
		
		<a href="javascript:void(0);">
			<i class="fas fa-folder"></i>
			Ordenes Manufactura Lista<br> para Recibir el Inventario
		</a>
		
		<hr>

		<a href="javascript:void(0);">
			<i class="fas fa-folder"></i>
			Configuración
		</a>
		
		<a href="javascript:void(0);">
			<i class="fas fa-folder"></i> 
			Salir
		</a>
	</nav>
	
	<main class="main">
		<h3 class="title-main">
			Monitores
		</h3>
		
		<div class="grid-videos">
			
			
		</div>
	</main>
</div>
<!-- partial -->
  <script  src="./script.js"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <img src="C:\Users\luisa.mejia\Downloads\Nueva carpeta\youtube\youtube\img\img_max.png"  width="400px" height="340px" >
    <section class="form-login">
      <h5>Login</h5>
      <input class="controls" type="text" name="usuario" value="" placeholder="Usuario">
      <input class="controls" type="password" name="contrasena" value="" placeholder="Contraseña">
      <a class="buttons"  href="{% url 'visual:home' %}" name="">Iniciar sesión</a>
      <p><a href="#">¿Olvidaste tu Contraseña?</a></p>
    </section>
  </body>
</html>